on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: List output files
        run: find build/ -print

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ftpes://ftp.world4you.com
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
